# docker-compose
version: '3.8'
services:
  app:
    build: .
    command: sh -c "pnpm start"
    ports:
      - 4200:4200
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
      - .pnpm-store:/home/node/app/.pnpm-store
volumes:
  node_modules:
  .pnpm-store: