# Dockerfile
FROM node:20.11.0-alpine as angular-app-creator
ENV PNPM_HOME=/usr/local/bin

# # RUN npm install -g pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate
RUN npm install -g npm@10.4.0
RUN apk update && pnpm install -g @angular/cli
WORKDIR /todo-app
CMD ["/bin/sh"]